version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: cryptodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/danjel/code/crypto-dashboard/crypto-db/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
