version: "3.1"
services:
  mongodb:
    image: mongo
    container_name: crypto-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
